# Example profile for desktop setup
PLATFORM=arch
SELECTED_SCRIPTS=(
  "cli_nvim"
  "cli_tmux"
  "cli_git"
  "cli_zsh"
  "cli_file_manager"
  "cli_system_info"
  "cli_networking"
  "cli_search"
  "cli_stow"
  "gui_hyprland_wm"
  "gui_audio"
  "gui_terminal"
  "gui_browser"
  "gui_file_manager"
  "gui_notifications"
  "gui_launcher"
  "gui_theming"
  "gui_fonts"
  "gui_disk_utils"
  "gui_portals"
)